---

- name: Network Getting Started First Playbook
  connection: network_cli
  hosts: palace
  tasks:

    - name: Get config for ios
      ios_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "{{ ansible_net_neighbors }}"



    - name: Display the config
      debug:
        msg: "{{ ansible_net_neighbors.items()}}"
